In [1]:
import pandas as pd
import numpy as np

База: загрузка датасета

In [2]:
data = pd.read_csv('data_ab.csv')

In [3]:
data.head()

   user_id                   timestamp      group landing_page  converted
0   851104  2025-01-21 22:11:48.556739    control     old_page          0
1   804228  2025-01-12 08:01:45.159739    control     old_page          0
2   661590  2025-01-11 16:55:06.154213  treatment     new_page          0
3   853541  2025-01-08 18:28:03.143765  treatment     new_page          0
4   864975  2025-01-21 01:52:26.210827    control     old_page          1

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 294478 entries, 0 to 294477
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   user_id       294478 non-null  int64
 1   timestamp     294478 non-null  object
 2   group         294478 non-null  object
 3   landing_page  294478 non-null  object
 4   converted     294478 non-null  int64
dtypes: int64(2), object(3)
memory usage: 11.2+ MB

In [23]:
data.isna().sum()

user_id         0
timestamp       0
group           0
landing_page    0
converted       0
dtype: int64

пропусков нет

In [24]:
data.describe()

             user_id      converted
count  294478.000000  294478.000000
mean   787974.124733       0.119659
std     91210.823776       0.324563
min    630000.000000       0.000000
25%    709032.250000       0.000000
50%    787933.500000       0.000000
75%    866911.750000       0.000000
max    945999.000000       1.000000

In [40]:
data['timestamp'] = pd.to_datetime(data['timestamp'])
data['date'] = data['timestamp'].dt.date
data['time'] = data['timestamp'].dt.time

In [41]:
data.head()

,user_id,timestamp,group,landing_page,converted,date,time
0,851104,2025-01-21 22:11:48.556739,control,old_page,0,2025-01-21,22:11:48.556739
1,804228,2025-01-12 08:01:45.159739,control,old_page,0,2025-01-12,08:01:45.159739
2,661590,2025-01-11 16:55:06.154213,treatment,new_page,0,2025-01-11,16:55:06.154213
3,853541,2025-01-08 18:28:03.143765,treatment,new_page,0,2025-01-08,18:28:03.143765
4,864975,2025-01-21 01:52:26.210827,control,old_page,1,2025-01-21,01:52:26.210827

Посмотрим разделение по классам

In [42]:
print(data['group'].value_counts()) #без принта почему-то криво выводит

group
treatment    147276
control      147202
Name: count, dtype: int64

In [43]:
print(data['converted'].value_counts())

converted
0    259241
1     35237
Name: count, dtype: int64

In [44]:
size = len(data)

In [45]:
print(data['group'].value_counts()/size)

group
treatment    0.500126
control      0.499874
Name: count, dtype: float64

распределение групп почти 50/50

In [46]:
print(data['converted'].value_counts()/size)

converted
0    0.880341
1    0.119659
Name: count, dtype: float64

88% пользователей не совершают целевое действие независимо от группы

In [47]:
group_a = data[data['group'] == 'control']
group_b = data[data['group'] == 'treatment']

size_a = len(group_a)
size_b = len(group_b)

In [48]:
print(group_a['converted'].value_counts()/size_a)
print(group_b['converted'].value_counts()/size_b)

converted
0    0.879601
1    0.120399
Name: count, dtype: float64
converted
0    0.88108
1    0.11892
Name: count, dtype: float64

Исходя из полученных данных мы можем предположить, что новая версия страницы сделала только хуже. Она уменьшает конверсию на 1%.

Но делать такие поспешные выводы мы не можем, так как у нас нет статистически значимых оснований так говорить.

Посмотрим на колонку с временем.