In [279]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots

База: загрузка датасета

In [280]:
data = pd.read_csv('data_ab.csv')

In [281]:
data.head()

   user_id                   timestamp      group landing_page  converted
0   851104  2025-01-21 22:11:48.556739    control     old_page          0
1   804228  2025-01-12 08:01:45.159739    control     old_page          0
2   661590  2025-01-11 16:55:06.154213  treatment     new_page          0
3   853541  2025-01-08 18:28:03.143765  treatment     new_page          0
4   864975  2025-01-21 01:52:26.210827    control     old_page          1

In [282]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 294478 entries, 0 to 294477
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   user_id       294478 non-null  int64
 1   timestamp     294478 non-null  object
 2   group         294478 non-null  object
 3   landing_page  294478 non-null  object
 4   converted     294478 non-null  int64
dtypes: int64(2), object(3)
memory usage: 11.2+ MB

In [283]:
data.isna().sum()

user_id         0
timestamp       0
group           0
landing_page    0
converted       0
dtype: int64

пропусков нет

In [284]:
data.describe()

             user_id      converted
count  294478.000000  294478.000000
mean   787974.124733       0.119659
std     91210.823776       0.324563
min    630000.000000       0.000000
25%    709032.250000       0.000000
50%    787933.500000       0.000000
75%    866911.750000       0.000000
max    945999.000000       1.000000

In [285]:
data['timestamp'] = pd.to_datetime(data['timestamp'])
data['date'] = data['timestamp'].dt.date
data['weekday'] = data['timestamp'].dt.weekday

In [286]:
data.head()

,user_id,timestamp,group,landing_page,converted,date,weekday
0,851104,2025-01-21 22:11:48.556739,control,old_page,0,2025-01-21,1
1,804228,2025-01-12 08:01:45.159739,control,old_page,0,2025-01-12,6
2,661590,2025-01-11 16:55:06.154213,treatment,new_page,0,2025-01-11,5
3,853541,2025-01-08 18:28:03.143765,treatment,new_page,0,2025-01-08,2
4,864975,2025-01-21 01:52:26.210827,control,old_page,1,2025-01-21,1

Посмотрим разделение по классам

In [287]:
print(data['group'].value_counts()) #без принта почему-то криво выводит

group
treatment    147276
control      147202
Name: count, dtype: int64

In [288]:
print(data['converted'].value_counts())

converted
0    259241
1     35237
Name: count, dtype: int64

In [289]:
size = len(data)

In [290]:
print(data['group'].value_counts()/size)

group
treatment    0.500126
control      0.499874
Name: count, dtype: float64

распределение групп почти 50/50

In [291]:
print(data['converted'].value_counts()/size)

converted
0    0.880341
1    0.119659
Name: count, dtype: float64

88% пользователей не совершают целевое действие независимо от группы

In [292]:
group_a = data[data['group'] == 'control']
group_b = data[data['group'] == 'treatment']

size_a = len(group_a)
size_b = len(group_b)

In [293]:
print(group_a['converted'].value_counts()/size_a)
print(group_b['converted'].value_counts()/size_b)

print(group_a['converted'].mean())
print(group_b['converted'].mean())

converted
0    0.879601
1    0.120399
Name: count, dtype: float64
converted
0    0.88108
1    0.11892
Name: count, dtype: float64
0.12039917935897611
0.11891957956489856

Исходя из полученных данных мы можем предположить, что новая версия страницы сделала только хуже. Она уменьшает конверсию на 1%.

Но делать такие поспешные выводы мы не можем, так как у нас нет статистически значимых оснований так говорить.

Посмотрим на колонку с временем.

In [294]:
group_by_date = data.groupby('date')['converted'].mean()

In [295]:
group_by_date

date
2025-01-02    0.122774
2025-01-03    0.113633
2025-01-04    0.119166
2025-01-05    0.118790
2025-01-06    0.120195
2025-01-07    0.118153
2025-01-08    0.119876
2025-01-09    0.119056
2025-01-10    0.119870
2025-01-11    0.117539
2025-01-12    0.122279
2025-01-13    0.114292
2025-01-14    0.123115
2025-01-15    0.117481
2025-01-16    0.120882
2025-01-17    0.124756
2025-01-18    0.124577
2025-01-19    0.118483
2025-01-20    0.116479
2025-01-21    0.121039
2025-01-22    0.118528
2025-01-23    0.123455
2025-01-24    0.119395
Name: converted, dtype: float64

Мы получили общую конверсию по датам независимо от группы

In [296]:
conversion = go.Scatter(x=group_by_date.index, y=group_by_date.values)

fig = go.Figure(conversion, layout_title_text="График конверсии по датам, независимо от группы")

fig.show()

In [297]:
group_A_by_date = group_a.groupby('date')['converted'].mean()

In [298]:
group_A_by_date

date
2025-01-02    0.125086
2025-01-03    0.113704
2025-01-04    0.121713
2025-01-05    0.122515
2025-01-06    0.116397
2025-01-07    0.120545
2025-01-08    0.118925
2025-01-09    0.119851
2025-01-10    0.113121
2025-01-11    0.119051
2025-01-12    0.122298
2025-01-13    0.117160
2025-01-14    0.126903
2025-01-15    0.120869
2025-01-16    0.122101
2025-01-17    0.122254
2025-01-18    0.124658
2025-01-19    0.119280
2025-01-20    0.115152
2025-01-21    0.125898
2025-01-22    0.119251
2025-01-23    0.125903
2025-01-24    0.118342
Name: converted, dtype: float64

In [299]:
group_B_by_date = group_b.groupby('date')['converted'].mean()

In [300]:
group_B_by_date

date
2025-01-02    0.120457
2025-01-03    0.113562
2025-01-04    0.116609
2025-01-05    0.115093
2025-01-06    0.123904
2025-01-07    0.115769
2025-01-08    0.120824
2025-01-09    0.118260
2025-01-10    0.126586
2025-01-11    0.116021
2025-01-12    0.122260
2025-01-13    0.111398
2025-01-14    0.119361
2025-01-15    0.114006
2025-01-16    0.119657
2025-01-17    0.127281
2025-01-18    0.124497
2025-01-19    0.117683
2025-01-20    0.117777
2025-01-21    0.116055
2025-01-22    0.117813
2025-01-23    0.120987
2025-01-24    0.120472
Name: converted, dtype: float64

In [301]:
figA = go.Scatter(x=group_A_by_date.index, y=group_A_by_date.values, name='Группа A')
figB = go.Scatter(x=group_B_by_date.index, y=group_B_by_date.values, name='Группа B')

data_new = [figA, figB]

fig = go.Figure(data_new, layout_title_text="Графики конверсии по датам для групп A и B")

fig.show()

In [302]:
group_by_weekday = data.groupby('weekday')['converted'].mean()

In [303]:
days = {0: 'Понедельник', 1: 'Вторник', 2: 'Среда', 3: 'Четверг', 4: 'Пятница', 5: 'Суббота', 6: 'Воскресенье'}

In [304]:
group_by_weekday

weekday
0    0.117010
1    0.120766
2    0.118632
3    0.121342
4    0.119409
5    0.120408
6    0.119857
Name: converted, dtype: float64

In [305]:
group_by_weekday.index = group_by_weekday.index.map(days)

In [306]:
conversion = go.Scatter(x=group_by_weekday.index, y=group_by_weekday.values)

fig = go.Figure(conversion, layout_title_text="График конверсии по дням недели, независимо от группы")

fig.show()

In [308]:
group_A_by_weekday = group_a.groupby('weekday')['converted'].mean()

In [309]:
group_A_by_weekday

weekday
0    0.116238
1    0.124454
2    0.119686
3    0.122937
4    0.116669
5    0.121778
6    0.121354
Name: converted, dtype: float64

In [310]:
group_A_by_weekday.index = group_A_by_weekday.index.map(days)

In [311]:
group_B_by_weekday = group_b.groupby('weekday')['converted'].mean()

In [312]:
group_B_by_weekday

weekday
0    0.117772
1    0.117063
2    0.117574
3    0.119739
4    0.122159
5    0.119043
6    0.118368
Name: converted, dtype: float64

In [313]:
group_B_by_weekday.index = group_B_by_weekday.index.map(days)

In [314]:
figA = go.Scatter(x=group_A_by_weekday.index, y=group_A_by_weekday.values, name='Группа A')
figB = go.Scatter(x=group_B_by_weekday.index, y=group_B_by_weekday.values, name='Группа B')

data_new = [figA, figB]

fig = go.Figure(data_new, layout_title_text="Графики конверсии по дням недели для групп A и B")

fig.show()